[book]
authors = ["Fewnity"]
language = "en"
src = "src"
title = "Xenity Engine"

[output.html.fold]
enable = true

[output.html]
additional-css = ["custom.css"]

# https://github.com/lambdalisue/rs-mdbook-alerts
[preprocessor.alerts]